[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

; 串口监视器核心配置
monitor_speed = 115200
monitor_echo = yes
monitor_eol = CRLF
monitor_filters = default, time, esp32_exception_decoder
lib_deps = claws/BH1750@^1.3.0